-- MySQL Script generated by MySQL Workbench
-- Thu Nov 30 12:21:07 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mbtadb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mbtadb` ;

-- -----------------------------------------------------
-- Schema mbtadb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mbtadb` DEFAULT CHARACTER SET utf8 ;
USE `mbtadb` ;

-- -----------------------------------------------------
-- Table `mbtadb`.`RoutesLinesMap`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mbtadb`.`RoutesLinesMap` ;

CREATE TABLE IF NOT EXISTS `mbtadb`.`RoutesLinesMap` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `route` VARCHAR(45) NULL,
  `line` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `mbtadb`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mbtadb`.`users` ;

CREATE TABLE IF NOT EXISTS `mbtadb`.`users` (
  `id` INT NOT NULL  AUTO_INCREMENT,
  `username` VARCHAR(45) NULL UNIQUE,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- sample user data
-- -----------------------------------------------------
INSERT INTO users (username, password) VALUES ('user@email.com', 'pass');


-- -----------------------------------------------------
-- Data created using python translator script json2sql.py
-- -----------------------------------------------------
INSERT INTO RoutesLinesMap (route, line) VALUES ('South Station', 'CR-Fairmount');
INSERT INTO RoutesLinesMap (route, line) VALUES ('South Station', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('South Station', 'CR-Franklin');
INSERT INTO RoutesLinesMap (route, line) VALUES ('South Station', 'CR-Greenbush');
INSERT INTO RoutesLinesMap (route, line) VALUES ('South Station', 'CR-Kingston');
INSERT INTO RoutesLinesMap (route, line) VALUES ('South Station', 'CR-Middleborough');
INSERT INTO RoutesLinesMap (route, line) VALUES ('South Station', 'CR-Needham');
INSERT INTO RoutesLinesMap (route, line) VALUES ('South Station', 'CR-Providence');
INSERT INTO RoutesLinesMap (route, line) VALUES ('South Station', 'CR-Foxboro');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Newmarket', 'CR-Fairmount');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Uphams Corner', 'CR-Fairmount');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Four Corners/Geneva', 'CR-Fairmount');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Talbot Avenue', 'CR-Fairmount');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Morton Street', 'CR-Fairmount');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Fairmount', 'CR-Fairmount');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Readville', 'CR-Fairmount');
INSERT INTO RoutesLinesMap (route, line) VALUES ('North Station', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('North Station', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('North Station', 'CR-Lowell');
INSERT INTO RoutesLinesMap (route, line) VALUES ('North Station', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Porter Square', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Belmont', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Waverly', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Waltham', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Brandeis/Roberts', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Kendal Green', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Hastings', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Silver Hill', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Lincoln', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Concord', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('West Concord', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('South Acton', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Littleton/Rte 495', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Ayer', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Shirley', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('North Leominster', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Fitchburg', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Wachusett', 'CR-Fitchburg');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Back Bay', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Back Bay', 'CR-Franklin');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Back Bay', 'CR-Needham');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Back Bay', 'CR-Providence');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Back Bay', 'CR-Foxboro');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Yawkey', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Boston Landing', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Newtonville', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('West Newton', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Auburndale', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Wellesley Farms', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Wellesley Hills', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Wellesley Square', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Natick Center', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('West Natick', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Framingham', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Ashland', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Southborough', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Westborough', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Grafton', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Worcester', 'CR-Worcester');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Ruggles', 'CR-Franklin');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Ruggles', 'CR-Needham');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Ruggles', 'CR-Providence');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Hyde Park', 'CR-Franklin');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Hyde Park', 'CR-Providence');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Readville', 'CR-Franklin');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Endicott', 'CR-Franklin');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Dedham Corp Center', 'CR-Franklin');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Dedham Corp Center', 'CR-Foxboro');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Islington', 'CR-Franklin');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Norwood Depot', 'CR-Franklin');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Norwood Central', 'CR-Franklin');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Plimptonville', 'CR-Franklin');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Windsor Gardens', 'CR-Franklin');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Walpole', 'CR-Franklin');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Norfolk', 'CR-Franklin');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Franklin', 'CR-Franklin');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Forge Park/495', 'CR-Franklin');
INSERT INTO RoutesLinesMap (route, line) VALUES ('JFK/UMASS', 'CR-Greenbush');
INSERT INTO RoutesLinesMap (route, line) VALUES ('JFK/UMASS', 'CR-Kingston');
INSERT INTO RoutesLinesMap (route, line) VALUES ('JFK/UMASS', 'CR-Middleborough');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Quincy Center', 'CR-Greenbush');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Quincy Center', 'CR-Kingston');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Quincy Center', 'CR-Kingston');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Quincy Center', 'CR-Middleborough');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Weymouth Landing/East Braintree', 'CR-Greenbush');
INSERT INTO RoutesLinesMap (route, line) VALUES ('East Weymouth', 'CR-Greenbush');
INSERT INTO RoutesLinesMap (route, line) VALUES ('West Hingham', 'CR-Greenbush');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Nantasket Junction', 'CR-Greenbush');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Cohasset', 'CR-Greenbush');
INSERT INTO RoutesLinesMap (route, line) VALUES ('North Scituate', 'CR-Greenbush');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Greenbush', 'CR-Greenbush');
INSERT INTO RoutesLinesMap (route, line) VALUES ('West Medford', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('West Medford', 'CR-Lowell');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Malden Center', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Wedgemere', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Wedgemere', 'CR-Lowell');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Wyoming Hill', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Winchester Center', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Winchester Center', 'CR-Lowell');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Melrose Cedar Park', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Melrose Highlands', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Anderson/Woburn', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Greenwood', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Wilmington', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Wilmington', 'CR-Lowell');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Wakefield', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Reading', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('North Wilmington', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Ballardvale', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Andover', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Lawrence', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Bradford', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Haverhill', 'CR-Haverhill');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Braintree', 'CR-Kingston');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Braintree', 'CR-Middleborough');
INSERT INTO RoutesLinesMap (route, line) VALUES ('South Weymouth', 'CR-Kingston');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Abington', 'CR-Kingston');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Whitman', 'CR-Kingston');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Hanson', 'CR-Kingston');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Halifax', 'CR-Kingston');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Kingston', 'CR-Kingston');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Plymouth', 'CR-Kingston');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Mishawum', 'CR-Lowell');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Anderson/Woburn', 'CR-Lowell');
INSERT INTO RoutesLinesMap (route, line) VALUES ('North Billerica', 'CR-Lowell');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Lowell', 'CR-Lowell');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Holbrook/Randolph', 'CR-Middleborough');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Montello', 'CR-Middleborough');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Brockton', 'CR-Middleborough');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Campello', 'CR-Middleborough');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Bridgewater', 'CR-Middleborough');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Middleborough/Lakeville', 'CR-Middleborough');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Forest Hills', 'CR-Needham');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Roslindale Village', 'CR-Needham');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Bellevue', 'CR-Needham');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Highland', 'CR-Needham');
INSERT INTO RoutesLinesMap (route, line) VALUES ('West Roxbury', 'CR-Needham');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Hersey', 'CR-Needham');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Needham Junction', 'CR-Needham');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Needham Center', 'CR-Needham');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Needham Heights', 'CR-Needham');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Chelsea', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('River Works', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Lynn', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Swampscott', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Salem', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Beverly', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('North Beverly', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Montserrat', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Prides Crossing', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Hamilton/Wenham', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Ipswich', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Beverly Farms', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Manchester', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Rowley', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Newburyport', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('West Gloucester', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Gloucester', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Rockport', 'CR-Newburyport');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Route 128', 'CR-Providence');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Canton Junction', 'CR-Providence');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Canton Center', 'CR-Providence');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Sharon', 'CR-Providence');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Mansfield', 'CR-Providence');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Stoughton', 'CR-Providence');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Attleboro', 'CR-Providence');
INSERT INTO RoutesLinesMap (route, line) VALUES ('South Attleboro', 'CR-Providence');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Providence', 'CR-Providence');
INSERT INTO RoutesLinesMap (route, line) VALUES ('TF Green Airport', 'CR-Providence');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Wickford Junction', 'CR-Providence');
INSERT INTO RoutesLinesMap (route, line) VALUES ('Foxboro', 'CR-Foxboro');

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
